{
    "docs": "https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.8` [[explain](https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/import.html)] failed with 1 error:", 
            "output": "plugins/modules/fusion_hap.py:249:9: traceback: SyntaxError: invalid escape sequence \\."
        }
    ], 
    "verified": false
}
